- name: Install Confluence
  hosts: confluence
  gather_facts: True
  vars:
    # https://developer.hashicorp.com/terraform/downloads
    # - terraform_version: 1.3.5

  roles:
      - role: mysql
        vars:
          mysql_databases:
            - name: "{{ confluence_database_name }}"
              collation: utf8mb4_bin
              encoding: utf8mb4
          mysql_users:
            - name: "{{ confluence_database_username }}"
              password: "{{ confluence_database_password }}"
              priv: '*.*:ALL'
      - role: confluence
