- name: Install Docker, Terraform, Helm, kubectl, aws-cli etc.
  hosts: localhost
  gather_facts: True
  vars:
    # https://developer.hashicorp.com/terraform/downloads
    - terraform_version: 1.7.1

  roles:
      - role: devops-tools
