---
- name: Copy notifications config file and setup email (Debian)
  ansible.builtin.copy:
    remote_src: yes
    src: /usr/lib/netdata/conf.d/health_alarm_notify.conf
    dest: /etc/netdata/health_alarm_notify.conf
  tags: notifications


- name: Update email recipient (Debian)
  ansible.builtin.lineinfile:
    path: /etc/netdata/health_alarm_notify.conf
    regexp: 'DEFAULT_RECIPIENT_EMAIL="root"'
    value: 'DEFAULT_RECIPIENT_EMAIL="{{ notifications_recipients }}"'
    state: present
  when: ansible_distribution == "Debian"
  tags: notifications
