---
- name: Run netdata install script
  ansible.builtin.command:
    cmd: /bin/bash -c "wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --no-updates --stable-channel --non-interactive"

- name: Set netdata path depending on OS
  set_fact:
    netdata_path: /opt/netdata 
  when: ansible_distribution == "Ubuntu"
  tags: always, netdata-path

- name: Copy customized netdata.conf file
  template:
    src: netdata.conf.j2
    dest: '{{ netdata_path | default("") }}/etc/netdata/netdata.conf'
  notify: restart netdata
  tags: config

- name: Copy go.d.conf config file
  copy:
    src: go.d.conf
    dest: '{{ netdata_path | default("") }}/etc/netdata/go.d.conf'
  notify: restart netdata
  tags: config

- name: Create systemdunits config file
  file:
    path: '{{ netdata_path | default("") }}/etc/netdata/go.d/systemdunits.conf'
    state: touch
  tags: config

- name: Copy notifications config file
  ansible.builtin.copy:
    remote_src: yes
    src:  '{{ netdata_path | default("") }}/usr/lib/netdata/conf.d/health_alarm_notify.conf'
    dest: '{{ netdata_path | default("") }}/etc/netdata/health_alarm_notify.conf'
  tags: notifications

- name: Update email recipient
  ansible.builtin.lineinfile:
    path: '{{ netdata_path | default("") }}/etc/netdata/health_alarm_notify.conf'
    regexp: 'DEFAULT_RECIPIENT_EMAIL="root"'
    value: 'DEFAULT_RECIPIENT_EMAIL="{{ notifications_recipients }}"'
    state: present
  tags: notifications

- name: Add netdata x509 certificate check
  template:
    src: conf.d/go.d/{{ item }}.j2
    dest: '{{ netdata_path | default("") }}/usr/lib/netdata/conf.d/go.d/{{ item }}'
  with_items:
    - x509check.conf
  notify: restart_netdata
    
