---
- name: Copy PCSX2 gamepad configurations
  copy:
      src: pcsx2_pad.ini
      dest: $HOME/.config/PCSX2/inis/PAD.ini

- name: Copy steam rom manager configuration
  copy:
      src: steam-rom-manager.json
      dest: $HOME/.config/steam-rom-manager/userData/userConfigurations.json

- name: Get RPCS3 Appimage
  get_url:
      url: https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-b9f2b1e7c6b4d1a37d8a9ec3e599d799c3f874be/rpcs3-v0.0.23-13843-b9f2b1e7_linux64.AppImage
      dest: "$HOME/Applications/"
