---
- name: Copy PCSX2 gamepad configurations
  copy:
      src: "gaming/pcsx2_pad.ini"
      dest: $HOME/.config/PCSX2/inis/PAD.ini

- name: Copy steam rom manager configuration
  copy:
      src: "gaming/steam-rom-manager.json"
      dest: $HOME/.config/steam-rom-manager/userData/userConfigurations.json

- name: Get RPCS3 Appimage
  get_url:
      url: https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-324b1039cf18828910521c813352e0ecacad8b96/rpcs3-v0.0.25-14373-324b1039_linux64.AppImage
      dest: "$HOME/Applications/"

- name: Copy Wireless Steam controller config for Retroarch
  copy: 
      src: "gaming/SC_Wireless_es.config"
      dest: /opt/retropie/configs/all/retroarch-joypads/

- name: Copy Emulation Station Steam controller config file
  copy:
      src: "gaming/emulation_station_steam_controller_config.cfg"
      dest: "$HOME/.emulationstation/es_input.cfg"
      owner: antisa
      group: antisa

- block:
  - name: Install sunshine game streaming server
    apt:
      deb: https://github.com/LizardByte/Sunshine/releases/download/{{ sunshine_version }}/sunshine-ubuntu-24.04-amd64.deb
    tags: sunshine

  - name: Set necessary capabilities for sunshine
    shell: sudo setcap cap_sys_admin+p $(readlink -f $(which sunshine))
    tags: sunshine

  become: true
  become_user: root
