---
confluence_version: 8.5.3
confluence_versions:
  8.5.3:
    url: https://product-downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-8.5.3-x64.bin
      
confluence_install_dir: /var/lib/confluence
confluence_home: "/opt/atlassian-confluence-{{ confluence_version }}"
confluence_owner: "confluence"
confluence_group: "confluence"

confluence_database_username: confluence
confluence_database_password: supersecure
confluence_database_host: localhost
confluence_database_port: "3306"
confluence_database_name: confluencedb
confluence_database_jdbc_url: jdbc:mysql://{{ confluence_database_host }}:{{ confluence_database_port }}/{{ confluence_database_name }}?sessionVariables=tx_isolation='READ-COMMITTED'

mysql_connector: mysql-connector-j-8.2.0
mysql_driver_url: https://cdn.mysql.com//Downloads/Connector-J/{{ mysql_connector }}.tar.gz

confluence_keystore: /opt/confluence/keystore

confluence_web_port: 8090
confluence_rmi_port: 8000

confluence_proxy_name: www.example.com
confluence_proxy_port: 80
confluence_web_port_https: 8443
confluence_web_context: /

confluence_max_http_header_size: 8192


