---
- name: Debian 11 tasks
  include: debian11.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '11'
  
- name: Debian 12 tasks
  include: debian12.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '12'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ confluence_install_dir }}"

- name: Download installer
  get_url:
    url: "{{ confluence_versions[confluence_version]['url'] }}"
    dest: "{{ confluence_install_dir }}/{{ confluence_versions[confluence_version]['url']|basename }}"
    timeout: 3000
    mode: 1373
  register: get_url_result
  until: get_url_result is succeeded

- name: Copy response file
  template:
    dest: "{{ confluence_install_dir }}/reponse.varfile"
    src: response.varfile.j2
    mode: 0644
  tags: install

- name: Run installer
  command: "{{ confluence_install_dir }}/{{ confluence_versions[confluence_version]['url']|basename }} -q -varfile {{ confluence_install_dir }}/reponse.varfile"
  become: yes
  become_method: sudo
  become_user: "{{ confluence_versions[confluence_version]['installer_user']|default('root') }}"
  notify:
    - confluence-systemctl-restart
  tags: install

- name: chown confluence dir
  file:
    dest: "{{ confluence_install_dir }}"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    recurse: yes

- name: Update home path in properties file
  lineinfile:
    path: "{{ confluence_install_dir }}/confluence/WEB-INF/classes/confluence-init.properties"
    regexp: "# confluence.home="
    line: "confluence.home={{ confluence_home }}"

- name: Download mysql driver
  unarchive:
    remote_src: yes
    src: "{{ mysql_driver_url }}"
    dest: "{{ confluence_install_dir }}/confluence/WEB-INF/lib"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
  tags: driver

- name: Copy mysql driver to correct location
  copy:
    remote_src: yes
    src:  "{{ confluence_install_dir }}/confluence/WEB-INF/lib/{{ mysql_connector }}/{{ mysql_connector}}.jar"
    dest:  "{{ confluence_install_dir }}/confluence/WEB-INF/lib"

- name: Copy server.xml
  template:
    src: server.xml.j2
    dest: "{{ confluence_install_dir }}/conf/server.xml"
  tags: config

- include: nginx.yml
  tags: nginx, config

- include: service.yml
  tags: systemd

- name: INFO
  debug:
    msg: "Now visit the URL {{ confluence_proxy_name }} and start the installation. On db screen select connection string and append the \"?sessionVariables=tx_isolation='READ-COMMITTED'\"\ 
      query parameter"
