- name: Run specific installation on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: always, ubuntu

- name: Run specific installation on Debian
  include_tasks: debian.yml
  when: ansible_distribution == "Debian"
  tags: always, debian

- name: Install Terraform binary
  get_url:
    url: 'https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip'
    dest: /tmp/
    mode: '0755'
  tags: terraform

- name: Unarchive terraform
  unarchive:
    src: /tmp/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: $HOME/.local/bin/
  tags: terraform

- name: Install additional ansible plugins
  community.general.ansible_galaxy_install:
    type: collection
    name: "{{ item }}"
  loop:
    - community.docker
    - community.mysql

- name: Install kubectl snap
  command: snap install kubectl --classic
  become: true
  become_user: root

- name: Install helm snap
  command: snap install helm --classic
  become: true
  become_user: root

- name: Install eksctl
  shell: |
    # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
    ARCH=amd64
    PLATFORM=$(uname -s)_$ARCH

    curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"

    # (Optional) Verify checksum
    curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check

    tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz

    sudo mv /tmp/eksctl /usr/local/bin
  become: true
  become_user: root
  tags: aws, eks

- name: Install aws config files
  template:
    src: "aws/{{ item }}.j2"
    dest: "$HOME/.aws/{{ item }}"
  loop:
    - config
    - credentials
  tags: aws, config
