- name: Run specific installation on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: always, ubuntu

- name: Run specific installation on Debian
  include_tasks: debian.yml
  when: ansible_distribution == "Debian"
  tags: always, debian

- name: Install Terraform binary
  get_url:
    url: 'https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip'
    dest: /tmp/
    mode: '0755'
  tags: terraform

- name: Unarchive terraform
  unarchive:
    src: /tmp/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: $HOME/.local/bin/
  tags: terraform

- name: Install terraform autocomplete
  shell: terraform -install-autocomplete
  tags: terraform

- name: Install additional ansible plugins
  community.general.ansible_galaxy_install:
    type: collection
    name: "{{ item }}"
  loop:
    - community.docker
    - community.mysql

- block:
  - name: Install ansible repo
    apt_repository:
        repo: ppa:ansible/ansible
        state: present
    tags: ansible
  
  - name: Install ansible
    apt:
      name:
        - ansible
    tags: ansible

  - name: Install kubectl snap
    command: snap install kubectl --classic

  - name: Install helm snap
    command: snap install helm --classic

  - name: Install eksctl
    shell: |
      # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
      ARCH=amd64
      PLATFORM=$(uname -s)_$ARCH

      curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"

      # (Optional) Verify checksum
      curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check

      tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz

      sudo mv /tmp/eksctl /usr/local/bin
    tags: aws, eks

  - name: Install github cli
    shell: |
      type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
      && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
      && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
      && sudo apt update \
      && sudo apt install gh -y
    tags: gh, github

  become: true
  become_user: root

- name: Install aws config files
  template:
    src: "aws/{{ item }}.j2"
    dest: "$HOME/.aws/{{ item }}"
  loop:
    - config
    - credentials
  tags: aws, config

# https://cloud.google.com/sdk/docs/install
- name: Install Google cloud tool - gcloud
  shell: |
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    sudo apt-get update && sudo apt-get -y install google-cloud-cli

- name: Print info about gcloud
  debug:
    msg: "Remember to run gcloud init after gcloud installation"

- name: Install pulumi
  shell: |
    curl -fsSL https://get.pulumi.com | sh
  tags: pulumi

