- block:
  - name: Install needed pkgs
    apt:
        name:
            - gnupg
            - ca-certificates
            - curl
            - lsb-release
            - ipcalc
        state: latest
        update_cache: yes
    tags: ubuntu

  become: true
  become_user: root
