- block:
  - name: Install vagrant repo
    shell:
      wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    tags: vagrant

  - name: Install needed pkgs
    apt:
        name:
            - gnupg
            - ca-certificates
            - curl
            - lsb-release
            - ipcalc
            - vagrant
        state: latest
        update_cache: yes
    tags: ubuntu

  become: true
  become_user: root

- name: Add vagrant autocomplete
  command: vagrant autocomplete install
  tags: vagrant
