---
- name: Install required packages
  apt:
    name:
      - python3-pip
      - vim

- name: Install pip docker package
  pip:
    extra_args: --break-system-packages
    name:
      - docker

- name: Run specific installation on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Run specific installation on Debian
  include_tasks: debian.yml
  when: ansible_distribution == "Debian" and ansible_architecture == "x86_64"

- name: Run specific installation on Raspberry Pi Debian
  include_tasks: rpi.yml
  when: ansible_distribution == "Debian" and ansible_architecture == "aarch64"
