---
- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Install required packages
  apt:
    name: 
        - openssl
    state: present

- name: "Create required directories in /etc/letsencrypt"
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x
  with_items:
  - account
  - certs
  - csrs
  - keys

- name: "Generate a Let's Encrypt account key"
  shell: "if [ ! -f {{ letsencrypt_account_key }} ]; then openssl genrsa 4096 | sudo tee {{ letsencrypt_account_key }}; fi"

- name: "Generate Let's Encrypt private key"
  shell: "openssl genrsa 4096 | sudo tee /etc/letsencrypt/keys/{{ letsencrypt_domain }}.key"

- name: "Generate Let's Encrypt CSR"
  shell: "openssl req -new -sha256 -key /etc/letsencrypt/keys/{{ letsencrypt_domain }}.key -subj \"/CN={{ letsencrypt_domain }}\" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf \"\n[SAN]\nsubjectAltName=DNS:{{ letsencrypt_domain }}\")) | sudo tee /etc/letsencrypt/csrs/{{ letsencrypt_domain }}.csr"
  args:
    executable: /bin/bash

- name: "Begin Let's Encrypt challenges"
  letsencrypt:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    terms_agreed: 1
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain }}.crt"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ letsencrypt_domain }}.crt"
    remaining_days: 91
  register: acme_challenge


- name: Copy nginx config file for ACME challenge
  template:
      src: nginx-acme.j2
      dest: /etc/nginx/sites-enabled/nginx-acme

- name: "Create .well-known/acme-challenge directory"
  file:
    path: /var/www/le/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Reload nginx conf immediately
  service:
    name: nginx
    state: reloaded

- name: "Implement http-01 challenge files"
  copy:
    content: "{{ acme_challenge['challenge_data'][item]['http-01']['resource_value'] }}"
    dest: "/var/www/le/{{ acme_challenge['challenge_data'][item]['http-01']['resource'] }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - "{{ letsencrypt_domain }}"

- name: "Complete Let's Encrypt challenges"
  letsencrypt:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain }}.crt"
    chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ letsencrypt_domain }}.crt"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ letsencrypt_domain }}"
    data: "{{ acme_challenge }}"

- name: Cleanup files
  file:
      path: "{{ item }}"
      state: absent
  loop:
      - /etc/nginx/sites-enabled/nginx-acme
      - /var/www/le

