---
- name: Install additional packages
  apt:
    name:
      - luarocks
      - ripgrep
    update_cache: yes
  become: true
  become_user: root
  tags: packages

- name: Download latest nvim appimage
  get_url:
    url: "{{ neovim_version }}"
    dest: $HOME/Applications/
    mode: 0755

- name: Create nvim symlink
  file:
    src: $HOME/Applications/{{ neovim_version }}
    dest: /usr/local/bin/nvim
    mode: 0775
    state: link
    
- name: Copy nvim config files
  copy:
    src: nvim
    dest: $HOME/.config/
  tags: config, nvim-config
