---
- name: Install packages
  apt:
      name: 
        - minidlna
        - openvpn
        - transmission-cli
        - tmux
        - dnsutils
  tags: packages

- name: Copy root user ssh keys to rpi
  authorized_key:
      key: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') }}" 
      user: root

- name: Copy transmission config
  copy:
      src: "transmission.json"
      dest: "/etc/transmission-daemon/settings.json"
  notify: Restart transmission

- name: Copy minidlna config
  copy:
      src: "minidlna.conf"
      dest: "/etc/minidlna.conf"
  notify: Restart minidlna

- name: Copy service files
  copy:
      src: "{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
  loop:
    - protonvpn-ch.service
    - vpn-nat.service
  tags: nat, proton

- name: Checkout newer natpmpc version
  git:
    repo: https://github.com/miniupnp/libnatpmp.git
    dest: /root
    depth: 1
  tags: nat

- name: Compile newer natpmpc version
  community.general.make:
    chdir: /root/libnatpmp
    targets:
      - all
      - Install
  tags: nat

- name: Reload systemd daemon
  systemd:
      daemon_reload: yes
  tags: nat, proton

- name: Copy openvpn configs
  copy:
      src: "{{ item }}"
      dest: "/root/"
  loop:
     - "ch.protonvpn.udp.ovpn"
     - "vpn-nat.sh"
  notify: 
   - Restart openvpn
   - Start protonvpn-ch
   - Start vpn-nat
  tags: nat, proton

- name: Copy openvpn creds
  template:
      src: "{{ item }}.j2"
      dest: "/root/{{ item }}"
  loop:
     - "protonvpn.login"
  notify: 
   - Restart openvpn
   - Start protonvpn-ch
   - Start vpn-nat
  tags: nat, proton

- name: Add cronjob to restart protonvpn-ch.service
  cron:
      name: "restart vpn"
      state: present
      minute: "0"
      hour: "0,6,12,18"
      job: "ping -c 1 1.1.1.1 || systemctl restart protonvpn-ch.service"

- name: Add cronjob to restart vpn-nat
  cron:
      name: "restart vpn-nat every 3h"
      state: present
      minute: "15"
      hour: "*/3"
      job: "systemctl restart vpn-nat.service"

